POST http://localhost:3000/api/products
Content-Type: application/json


{
	"categoria": "Maquiagem",
	"nome": "Pincel de maquiagem",
	"descrição": "Um pincel de maquiagem é um produto de maquiagem que é usado para aplicar a maquiagem.",
	"preço": 20,
	"estoque": 50,
	"favorito": 5
}




### Consulta todos os serviços
GET  http://localhost:3000/api/products

### Consulta serviços por ID

GET  http://localhost:3000/api/products/64e4ed76e632a1b1df7d8729


### Deleta serviços por ID

GET http://localhost:3000/api/products/delete/64e4ceffb6bc6801f51032e2

### Atualização de seviço
PUT  http://localhost:3000/api/products/update/64e4ed76e632a1b1df7d8729
Content-Type: application/json

{
	"categoria": "Maquiagem",
	"nome": "Pincel de maquiagem",
	"descrição": "Um pincel de maquiagem é um produto de maquiagem que é usado para aplicar a maquiagem.",
	"preço": 20,
	"estoque": 50,
	"favorito": 10
}
	
